-- 查看MV LOG的大小
SELECT S.OWNER,
       S.SEGMENT_NAME,
       S.SEGMENT_TYPE,
       S.TABLESPACE_NAME,
       ROUND(S.BYTES / 1024 / 1024 / 1024, 1) SIZE_GB
  FROM DBA_SEGMENTS S
 WHERE S.SEGMENT_NAME IN
       ('MLOG$_AP_SUPPLIER_SITES_AL', 'MLOG$_AP_SUPPLIERS')
;


-- 查看MV LOG对应的主表
SELECT T.LOG_OWNER, T.MASTER, T.LOG_TABLE
  FROM DBA_MVIEW_LOGS T
 WHERE T.LOG_TABLE IN ('MLOG$_AP_SUPPLIER_SITES_AL', 'MLOG$_AP_SUPPLIERS');
 
 
-- 查看依赖主表的物化视图
SELECT *
  FROM DBA_DEPENDENCIES DD
 WHERE DD.REFERENCED_NAME IN ('AP_SUPPLIERS','AP_SUPPLIER_SITES_ALL')
   AND TYPE = 'MATERIALIZED VIEW';
   

-- 查看MVIEW记录多少
SELECT 'POA_IDL_BS_J_MV: ' || COUNT(*) AS COUNT
  FROM POA_IDL_BS_J_MV
UNION ALL
SELECT 'POA_ITEMS_MV: ' || COUNT(*)
  FROM POA_ITEMS_MV
UNION ALL
SELECT 'POA_MID_BS_J_MV: ' || COUNT(*)
  FROM POA_MID_BS_J_MV;
   
   
-- 查看MVIEW属性
SELECT T.OWNER,
       T.MVIEW_NAME,
       T.REFRESH_MODE,
       T.REFRESH_METHOD,
       T.LAST_REFRESH_TYPE,
       T.LAST_REFRESH_DATE,
       T.STALENESS,
       T.STALE_SINCE
  FROM DBA_MVIEWS T
 WHERE T.MVIEW_NAME IN
       ('POA_IDL_BS_J_MV', 'POA_ITEMS_MV', 'POA_MID_BS_J_MV');
