SELECT OCCUPANT_NAME, SPACE_USAGE_KBYTES FROM V$SYSAUX_OCCUPANTS;

SELECT * FROM DBA_HIST_WR_CONTROL;

SELECT DBMS_STATS.GET_STATS_HISTORY_RETENTION FROM DUAL;

SELECT *
  FROM SYS.WRI$_OPTSTAT_HISTHEAD_HISTORY T
ORDER BY T.SAVTIME   
  ;

/*   	COUNT(*) 1237002165*/

  SELECT COUNT(*)
    FROM ALL_PART_TABLES
   WHERE OWNER = 'SYS'
     AND TABLE_NAME = 'WRI$_OPTSTAT_HISTHEAD_HISTORY';
         
BEGIN
  DBMS_STATS.PURGE_STATS(SYSDATE - 400);
END;
/
