
SELECT 'WRI$_OPTSTAT_HISTHEAD_HISTORY' SEGMENT_NAME
          FROM DUAL
        UNION ALL
        SELECT I.INDEX_NAME
          FROM DBA_INDEXES I
         WHERE I.TABLE_NAME = 'WRI$_OPTSTAT_HISTHEAD_HISTORY'
        UNION ALL
        SELECT L.SEGMENT_NAME
          FROM DBA_LOBS L
         WHERE L.TABLE_NAME = 'WRI$_OPTSTAT_HISTHEAD_HISTORY'
         ;
         
         
SELECT S.SEGMENT_NAME,
       S.SEGMENT_TYPE,
       ROUND(S.BYTES / 1024 / 1024 / 1024) SIZE_GB
  FROM DBA_SEGMENTS S
 WHERE S.SEGMENT_NAME IN ('WRI$_OPTSTAT_HISTHEAD_HISTORY',
                          'I_WRI$_OPTSTAT_HH_ST',
                          'I_WRI$_OPTSTAT_HH_OBJ_ICOL_ST',
                          'SYS_IL0000000494C00016$$',
                          'SYS_LOB0000000494C00016$$')
                          ORDER BY S.BYTES DESC
                          ;


SELECT DBMS_STATS.GET_STATS_HISTORY_RETENTION FROM DUAL;

SELECT DBMS_STATS.GET_STATS_HISTORY_AVAILABILITY FROM DUAL;

SELECT MIN(SAVTIME), MAX(SAVTIME) FROM SYS.WRI$_OPTSTAT_HISTHEAD_HISTORY;

380

ALTER SESSION SET EVENTS '10046 trace name context forever, level 12';
dbms_stats.purge_stats(sysdate-380);
ALTER SESSION SET EVENTS '10046 trace name context off';
