SELECT R.REQUEST_ID,
       R.ACTUAL_START_DATE,
       P.USER_CONCURRENT_PROGRAM_NAME,
       TRUNC((R.ACTUAL_COMPLETION_DATE - R.ACTUAL_START_DATE) * 24) RUN_HOUR
  FROM FND_CONCURRENT_REQUESTS R, FND_CONCURRENT_PROGRAMS_TL P
 WHERE R.CONCURRENT_PROGRAM_ID = P.CONCURRENT_PROGRAM_ID
   AND R.ACTUAL_START_DATE IS NOT NULL
   AND P.USER_CONCURRENT_PROGRAM_NAME = 'CRC_B29_BI_ÏúÊÛ³ö¿â'
   AND P.LANGUAGE = 'ZHS'
 ORDER BY 1 DESC
