-- 统计请求运行次数
WITH RUN_TIMES AS
 (SELECT R.CONCURRENT_PROGRAM_ID,
         COUNT(*) COUNT
    FROM FND_CONCURRENT_REQUESTS R
   WHERE R.ACTUAL_START_DATE > SYSDATE - 30
   GROUP BY R.CONCURRENT_PROGRAM_ID)
SELECT P.USER_CONCURRENT_PROGRAM_NAME,
       P1.CONCURRENT_PROGRAM_NAME,
       T.COUNT
  FROM RUN_TIMES               T,
       FND_CONCURRENT_PROGRAMS_TL P,
       FND_CONCURRENT_PROGRAMS    P1
 WHERE T.CONCURRENT_PROGRAM_ID = P.CONCURRENT_PROGRAM_ID
   AND P1.CONCURRENT_PROGRAM_ID = P.CONCURRENT_PROGRAM_ID
   AND P.LANGUAGE = 'ZHS'
 ORDER BY T.COUNT DESC
