-- 统计请求平均运行时间
WITH AVG_RUN_TIME AS
 (SELECT R.CONCURRENT_PROGRAM_ID,
         ROUND(AVG((R.ACTUAL_COMPLETION_DATE - R.ACTUAL_START_DATE) * 24 * 60 * 60),
               1) RUN_SECONDS
    FROM FND_CONCURRENT_REQUESTS R
   WHERE R.ACTUAL_START_DATE > SYSDATE - 30
   GROUP BY R.CONCURRENT_PROGRAM_ID)
SELECT P.USER_CONCURRENT_PROGRAM_NAME,
       P1.CONCURRENT_PROGRAM_NAME,
       T.RUN_SECONDS
  FROM AVG_RUN_TIME               T,
       FND_CONCURRENT_PROGRAMS_TL P,
       FND_CONCURRENT_PROGRAMS    P1
 WHERE T.CONCURRENT_PROGRAM_ID = P.CONCURRENT_PROGRAM_ID
   AND P1.CONCURRENT_PROGRAM_ID = P.CONCURRENT_PROGRAM_ID
   AND P.LANGUAGE = 'ZHS'
 ORDER BY T.RUN_SECONDS DESC
