
WITH REQUEST_COUNT AS
 (SELECT TRUNC(R.REQUEST_DATE, 'HH24') S_DATE, COUNT(*) AMOUNT
    FROM FND_CONCURRENT_REQUESTS R
   WHERE R.REQUEST_DATE > SYSDATE - 30
   GROUP BY TRUNC(R.REQUEST_DATE, 'HH24')
   ORDER BY 1),
COMPLETE_COUNT AS
 (SELECT TRUNC(R.ACTUAL_COMPLETION_DATE, 'HH24') C_DATE, COUNT(*) AMOUNT
    FROM FND_CONCURRENT_REQUESTS R
   WHERE R.REQUEST_DATE > SYSDATE - 30
   GROUP BY TRUNC(R.ACTUAL_COMPLETION_DATE, 'HH24')
   ORDER BY 1)

SELECT to_char(S_DATE, 'yyyy-mm-dd hh24:mi:ss') || ' - ' ||
       TO_CHAR(S_DATE + 1 / 24, 'yyyy-mm-dd hh24:mi:ss') 时间,
       NVL(REQUEST_COUNT.AMOUNT, 0) 提交个数,
       NVL(COMPLETE_COUNT.AMOUNT, 0) 完成个数
  FROM REQUEST_COUNT
  FULL JOIN COMPLETE_COUNT
    ON REQUEST_COUNT.S_DATE = COMPLETE_COUNT.C_DATE
 ORDER BY 1
